config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'welcome#home'
  get 'signup', to: 'users#new', as: 'signup'
  get '/signin', to: 'sessions#new', as: 'login'
  post '/signin', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  get 'auth/:provider/callback', to: 'sessions#google_auth', as: 'google_login'
  get 'auth/failure', to: redirect('welcome#home')

  get 'welcome/privacy', to: 'welcome#privacy'
  get 'welcome/terms', to: 'welcome#terms'

  resources :users
  resources :sessions, only: [:create, :new]
  resources :lessons
  resources :bookings
  resources :skills
  resources :sections do
    resources :skills, only: [:new, :create]
  end

  resources :instructors do
    resources :reviews, only: [:index, :new, :create]
  end

  get '/rank' => 'instructors#rank', as: 'top3_instructors'
  # resources :instructors do
  #   get 'rank', :on => :collection, as: 'top3'
  # end
end

app/models/instructor.rb
class Instructor < ApplicationRecord
  mount_uploader :picture, PictureUploader

  has_many :lessons, :dependent => :destroy
  has_many :skills, through: :lessons
  has_many :reviews, :dependent => :destroy
  has_many :users, through: :reviews

  validates :name, presence: true

  scope :by_rating, -> { 
      joins(:reviews) 
      .group("instructors.id") 
      .order("AVG(reviews.rating) DESC, COUNT(reviews.id) DESC")
    }

  accepts_nested_attributes_for :reviews

  def average_rating
      if self.reviews.size > 0
          self.reviews.average(:rating).round(1)
      else
          'No ratings'
      end
  end

  def review_count
    if self.reviews.count == 0
      "No reviews."
    elsif self.reviews.count == 1
      "1 review"
    else
      "#{self.reviews.count} reviews"
    end
  end

  def self.top_rated 
    self.joins(:reviews)
        .where( :reviews => { :rating => [4, 5] })
        .group('instructors.id')
        .order('AVG(reviews.rating) DESC, COUNT(reviews.id) DESC')
  end
end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  before_action :set_instructor, only: [:show, :edit, :update, :destroy]
  before_action :admin_only, except: [:index, :show]

  def index
    @instructors = Instructor.all
  end

  def rank
    @instructors = Instructor.top_rated.limit(3)
    render :top3
  end

  def new
    @instructor = Instructor.new
  end

  def create
    @instructor = Instructor.new(instructor_params)

    respond_to do |format|
      if @instructor.save
        format.html { redirect_to @instructor, notice: 'The instructor was successfully created.' }
        format.json { render :show, status: :created, location: @instructor }
      else
        format.html { render :new }
        format.json { render json: @instructor.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @reviews = @instructor.reviews.all.order( 'created_at DESC')
  end

  def edit
  end

  def update
    respond_to do |format|
      if @instructor.update(instructor_params)
        format.html { redirect_to @instructor, notice: 'The instructor was successfully updated.' }
        format.json { render :show, status: :ok, location: @instructor }
      else
        format.html { render :edit }
        format.json { render json: @instructor.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
     @instructor.destroy
     respond_to do |format|
       format.html { redirect_to instructors_url, notice: 'instructor was successfully deleted.' }
       format.json { head :no_content }
     end
  end

  private
    # Use callbacks to share common setup between actions.
    def set_instructor
      @instructor = Instructor.find(params[:id])
    end

    # Never trust parameters from the internet, only allow the whitelist through.
    def instructor_params
      params.require(:instructor).permit(:name, :bio, :class_time, :picture, :picture_cache)
    end
end

app/views/instructors/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for instructor do |f| %>
      <%= render 'shared/errors', object: instructor %>

      <%= f.label "Name: " %>
      <%= f.text_field :name %><br>
      <%= f.label "Bio: " %>
      <%= f.text_area :bio, size: "60x12" %><br>
      <%= f.label "Class Time: " %>
      <%= f.text_field :class_time %><br>
      <%= f.label "Add a picture: " %>
      <%= f.file_field :picture, id: :instructor_picture %><br>
      <%= f.hidden_field :picture_cache %>

      <%= f.submit "Submit", class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/instructors/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h3>Edit Instructor</h3>
  </div>
</div>
<%= render 'form', instructor: @instructor %>

app/views/instructors/index.html.erb
<h2>Instructors</h2>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Instructor</th>
      <th>Bio</th>
      <th>Class Schedule</th>
      <th>Average Rating</th>
    </tr>
  </thead>

  <tbody>
    <% @instructors.each do |instructor| %>
    <tr>
      <td><%= link_to instructor.name, instructor_path(instructor) %></td>
      <td><%= instructor.bio %></td>
      <td><%= instructor.class_time %></td>
      <td><%= instructor.average_rating %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<% if current_user && current_user.admin %>
    <%= link_to 'New Instructor', new_instructor_path, class: 'btn btn-primary' %>
<% end %>

app/views/instructors/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h3>New Instructor</h3>
  </div>
</div>
<%= render 'form', instructor: @instructor %>

app/views/instructors/show.html.erb
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style media="screen">
    .star-rating {
      font-size: 0;
      white-space: nowrap;
      display: inline-block;
      /* width: 250px; remove this */
      height: 50px;
      overflow: hidden;
      position: relative;
      background: url('data:image/svg+xml;base64,PHN2ZyB2ZXJzaW9uPSIxLjEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6eGxpbms9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGxpbmsiIHg9IjBweCIgeT0iMHB4IiB3aWR0aD0iMjBweCIgaGVpZ2h0PSIyMHB4IiB2aWV3Qm94PSIwIDAgMjAgMjAiIGVuYWJsZS1iYWNrZ3JvdW5kPSJuZXcgMCAwIDIwIDIwIiB4bWw6c3BhY2U9InByZXNlcnZlIj48cG9seWdvbiBmaWxsPSIjREREREREIiBwb2ludHM9IjEwLDAgMTMuMDksNi41ODMgMjAsNy42MzkgMTUsMTIuNzY0IDE2LjE4LDIwIDEwLDE2LjU4MyAzLjgyLDIwIDUsMTIuNzY0IDAsNy42MzkgNi45MSw2LjU4MyAiLz48L3N2Zz4=');
      background-size: contain;
    }
    .star-rating i {
      opacity: 0;
      position: absolute;
      left: 0;
      top: 0;
      height: 100%;
      /* width: 20%; remove this */
      z-index: 1;
      background: url('data:image/svg+xml;base64,PHN2ZyB2ZXJzaW9uPSIxLjEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6eGxpbms9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGxpbmsiIHg9IjBweCIgeT0iMHB4IiB3aWR0aD0iMjBweCIgaGVpZ2h0PSIyMHB4IiB2aWV3Qm94PSIwIDAgMjAgMjAiIGVuYWJsZS1iYWNrZ3JvdW5kPSJuZXcgMCAwIDIwIDIwIiB4bWw6c3BhY2U9InByZXNlcnZlIj48cG9seWdvbiBmaWxsPSIjRkZERjg4IiBwb2ludHM9IjEwLDAgMTMuMDksNi41ODMgMjAsNy42MzkgMTUsMTIuNzY0IDE2LjE4LDIwIDEwLDE2LjU4MyAzLjgyLDIwIDUsMTIuNzY0IDAsNy42MzkgNi45MSw2LjU4MyAiLz48L3N2Zz4=');
      background-size: contain;
    }
    .star-rating input {
      -moz-appearance: none;
      -webkit-appearance: none;
      opacity: 0;
      display: inline-block;
      /* width: 20%; remove this */
      height: 100%;
      margin: 0;
      padding: 0;
      z-index: 2;
      position: relative;
    }
    .star-rating input:hover + i,
    .star-rating input:checked + i {
      opacity: 1;
    }
    .star-rating i ~ i {
      width: 40%;
    }
    .star-rating i ~ i ~ i {
      width: 60%;
    }
    .star-rating i ~ i ~ i ~ i {
      width: 80%;
    }
    .star-rating i ~ i ~ i ~ i ~ i {
      width: 100%;
    }
    ::after,
    ::before {
      height: 100%;
      padding: 0;
      margin: 0;
      box-sizing: border-box;
      text-align: center;
      vertical-align: middle;
    }

    .star-rating.star-5 {width: 250px;}
    .star-rating.star-5 input,
    .star-rating.star-5 i {width: 20%;}
    .star-rating.star-5 i ~ i {width: 40%;}
    .star-rating.star-5 i ~ i ~ i {width: 60%;}
    .star-rating.star-5 i ~ i ~ i ~ i {width: 80%;}
    .star-rating.star-5 i ~ i ~ i ~ i ~i {width: 100%;}

</style>
</head>
<body>

<div class="instructor-profile">
  <div class="profile row">
    <div class="col-md-4 avatar">
      <div class="wrapper">
        <%= image_tag(@instructor.picture_url, size: "300x200", alt: "picture") if @instructor.picture.present? %>
      </div>
    </div>

    <div class="col-md-8 basic-info">
      <div class="instructor-wrapper">
        <h3 class="name"> <%= @instructor.name %></h3>
        <p class="name"> <%= @instructor.bio %></p>
        Teaching Schedule: <span class="name"> <%= @instructor.class_time %></span><br>
        Average Rating: <%= @instructor.average_rating %><br><br>
        <%= link_to "REVIEWS", instructor_reviews_path(@instructor, @instructor.reviews) %>
      </div>
    </div>
  </div>
</div>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Lesson</th>
      <th>city</th>
      <th>Price</th>
      <th>Available</th>
      <th>Seats left</th>
    </tr>
  </thead>

  <tbody>
    <% @instructor.lessons.each do |lesson| %>
    <tr>
      <td><%= link_to lesson.title, lesson_path(lesson) %></td>
      <td><%= lesson.city %></td>
      <td><%= number_to_currency(lesson.price) %></td>
      <td><%= human_boolean(lesson.available) %></td>
      <td><%= lesson.seats %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<% if current_user && current_user.admin %>
    <%= link_to "Edit Instructor", edit_instructor_path(@instructor.id), class: 'btn btn-info' %>
    <%= link_to "Delete Instructor", instructor_path(@instructor.id), data: {:confirm => 'Are you sure?'}, method: 'DELETE', class: 'btn btn-info' %>
<% elsif current_user %>
    <%= form_tag("/instructors/#{@instructor.id}/reviews", method: "post") do %>
        <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
        <%= hidden_field_tag :user_id, current_user.id %>
        <%= hidden_field_tag :instrucor_id, @instructor.id %>
        Like this instructor? Add a review: <br>
        Rating:
        <span class="star-rating star-5">
          <input type="radio" name="rating" value="1"><i></i>
          <input type="radio" name="rating" value="2"><i></i>
          <input type="radio" name="rating" value="3"><i></i>
          <input type="radio" name="rating" value="4"><i></i>
          <input type="radio" name="rating" value="5"><i></i>
        </span><br>
        Review: <textarea name="body" rows="3" cols="60"></textarea>
        <%= button_tag "Submit", class: 'btn btn-primary' %>
    <% end %>
<% else %>
        <br>
        Please <%= link_to "Sign up", new_user_path %> or
        <%= link_to "Log in", new_session_path %> to add reviews and comments.
<% end %>

app/views/instructors/top3.html.erb
<h2>Top 3 Instructors</h2>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Instructor</th>
      <th>Bio</th>
      <th>Class Schedule</th>
      <th>Average Rating</th>
    </tr>
  </thead>

  <tbody>
    <% @instructors.each do |instructor| %>
    <tr>
      <td><%= link_to instructor.name, instructor_path(instructor) %></td>
      <td><%= instructor.bio %></td>
      <td><%= instructor.class_time %></td>
      <td><%= instructor.average_rating %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<% if current_user && current_user.admin %>
    <%= link_to 'New Instructor', new_instructor_path, class: 'btn btn-primary' %>
<% end %>