config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'welcome#home'
  get 'signup', to: 'users#new', as: 'signup'
  get '/signin', to: 'sessions#new', as: 'login'
  post '/signin', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  get 'auth/:provider/callback', to: 'sessions#google_auth', as: 'google_login'
  get 'auth/failure', to: redirect('welcome#home')

  get 'welcome/privacy', to: 'welcome#privacy'
  get 'welcome/terms', to: 'welcome#terms'

  resources :users
  resources :sessions, only: [:create, :new]
  resources :lessons
  resources :bookings
  resources :skills
  resources :sections do
    resources :skills, only: [:new, :create]
  end

  resources :instructors do
    resources :reviews, only: [:index, :new, :create]
  end

  get '/rank' => 'instructors#rank', as: 'top3_instructors'
  # resources :instructors do
  #   get 'rank', :on => :collection, as: 'top3'
  # end
end

app/models/section.rb
class Section < ApplicationRecord
  has_many :skills, :dependent => :destroy

  accepts_nested_attributes_for :skills, :reject_if => lambda { |a| a[:name].blank? }, :allow_destroy => true
  validates :name, presence: true
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
	before_action :find_section, only: [:show, :edit, :update]
  before_action :admin_only, except: [:index, :show]

	def index
		@sections = Section.all.order('name ASC')
	end

	def new
		@section = Section.new
		3.times { @section.skills.build }
	end

	def show
		@skills = @section.skills.order('name ASC')
	end

	def create
	  @section = Section.new(section_params)

	  if @section.save  	
	  	redirect_to section_path(@section)
	  else
	  	render :new
	  end
	end

	def edit

	end

	def update

	  @section.update(section_params)
	  if @section.save
	  	redirect_to section_path(@section)
	  else
	  	render :edit
	  end
	end

	private

	def find_section
    @section = Section.find_by(id: params[:id])
  end

	def section_params
    params.require(:section).permit(:name, skills_attributes: [:id, :name, :section_id])
  end

end

app/views/sections/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for section do |f| %>
      <%= render 'shared/errors', object: section %>

      <%= f.label "Section Name: " %>
      <%= f.text_field :name %><br>
      <br>
      <%= f.fields_for :skills do |builder| %>
          <%= builder.label "Skill Name: " %>
          <%= builder.text_field :name %>
          <%= builder.check_box :_destroy %>
          <%= builder.label :_destroy, "Remove Skill" %><br>
      <% end %>
      <br>
      <%= f.submit "Submit", class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/sections/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h3>Edit Section</h3>
    <%= form_for @section do |f| %>
      <%= render 'shared/errors', object: @section %>

      <%= f.label "Section Name: " %>
      <%= f.text_field :name %><br>
      <br>
      <%= f.submit "Submit", class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/sections/index.html.erb
<h2>Explore Sections</h2>
<% @sections.each do |section| %>
  <h4><%= link_to section.name, section_path(section) %></h4>
  <% section.skills.each do |skill| %>
    <%= link_to skill.name, skill_path(skill.id) %><br>
  <% end %>
  <br>
<% end %>
<% if current_user && current_user.admin %>
    <%= link_to 'New Section', new_section_path, class: 'btn btn-primary' %>
<% end %>

app/views/sections/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h3>New Section</h3>
  </div>
</div>
<%= render 'form', section: @section %>

app/views/sections/show.html.erb
<h4><%= link_to "All Sections", sections_path %> > <%= @section.name %> </h4>
<h2><%= @section.name %></h2>
<% @section.skills.each do |skill| %>
  <h4><%= link_to skill.name, skill_path(skill.id) %></h4>
  <div class="lessons">
    <table class="table table-striped" style="width: 100%">
      <colgroup>
       <col span="1" style="width: 50%;">
       <col span="1" style="width: 20%;">
       <col span="1" style="width: 20%;">
       <col span="1" style="width: 10%;">
     </colgroup>
      <thead>
        <tr>
          <th>Lesson</th>
          <th>Instructor</th>
          <th>city</th>
          <th>Seats left</th>
        </tr>
      </thead>

      <tbody>
        <% skill.lessons.each do |lesson| %>
        <tr>
          <td><%= link_to lesson.title, lesson_path(lesson) %></td>
          <td><%= link_to lesson.instructor.name, instructor_path(lesson.instructor) %></td>
          <td><%= lesson.city %></td>
          <td><%= lesson.seats %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>
<% if current_user && current_user.admin %>
    <%= link_to "Add New Skill", new_section_skill_path(@section.id), class: 'btn btn-primary' %>
    <%= link_to "Edit Section", edit_section_path(@section.id), class: 'btn btn-primary' %>
<% end %>