config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'welcome#home'
  get 'signup', to: 'users#new', as: 'signup'
  get '/signin', to: 'sessions#new', as: 'login'
  post '/signin', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  get 'auth/:provider/callback', to: 'sessions#google_auth', as: 'google_login'
  get 'auth/failure', to: redirect('welcome#home')

  get 'welcome/privacy', to: 'welcome#privacy'
  get 'welcome/terms', to: 'welcome#terms'

  resources :users
  resources :sessions, only: [:create, :new]
  resources :lessons
  resources :bookings
  resources :skills
  resources :sections do
    resources :skills, only: [:new, :create]
  end

  resources :instructors do
    resources :reviews, only: [:index, :new, :create]
  end

  get '/rank' => 'instructors#rank', as: 'top3_instructors'
  # resources :instructors do
  #   get 'rank', :on => :collection, as: 'top3'
  # end
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :skill
  belongs_to :instructor
  has_many :bookings
  has_many :users, through: :bookings

  validates :title, presence: true
  scope :available, -> { where(available: true) }
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: [:show, :edit, :update, :destroy]
  before_action :admin_only, except: [:index, :show]

  def new
    @lesson = Lesson.new
  end

  def create
    @lesson = Lesson.new(lesson_params)

    respond_to do |format|
      if @lesson.save
        format.html { redirect_to @lesson, notice: 'Lesson was successfully created.' }
        format.json { render :show, status: :created, location: @lesson }
      else
        format.html { render :new }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  def index
    if params[:title]
        @lessons = Lesson.where('lower(title) LIKE ?', "%#{params[:title].downcase}%")
    else
        # if no filters are applied, show all available Lessons, sorted by created_at DESC
        @lessons = Lesson.order('created_at DESC')
    end
  end

  def show
  end

  def edit
  end

  def update
    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to @lesson, notice: 'Lesson was successfully updated.' }
        format.json { render :show, status: :ok, location: @lesson }
      else
        format.html { render :edit }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
     @lesson.destroy
     respond_to do |format|
       format.html { redirect_to lessons_url, notice: 'Lesson was successfully deleted.' }
       format.json { head :no_content }
     end
  end

  private
  # Use callbacks to share common setup between actions.
  def set_lesson
      @lesson = Lesson.find(params[:id])
  end

  # Never trust parameters from the internet, only allow the whitelist through.
  def lesson_params
      params.require(:lesson).permit(:title, :about, :price, :seats, :length, :requirement, :dates, :time, :available, :online, :address, :city, :state, :zipcode,:skill_id, :instructor_id)
  end
end

app/views/lessons/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for lesson do |f| %>
      <%= render 'shared/errors', object: lesson %>

      <%= f.label "Title" %>
      <%= f.text_field :title %><br>
      <%= f.label "About" %>
      <%= f.text_area :about, size: "60x12" %><br>
      <%= f.label "Price" %> dollars
      <%= f.text_field :price %><br>
      <%= f.label "Seats" %>
      <%= f.text_field :seats %><br>
      <%= f.label "Dates" %>
      <%= f.text_field :dates %><br>
      <%= f.label "Time" %>
      <%= f.text_field :time %><br>
      <%= f.label "Length" %> hour
      <%= f.text_field :length %><br>
      <%= f.label "Requirement" %>
      <%= f.text_field :requirement %><br>
      <p>Avaible? <%= f.check_box :available, options = {:class => "lesson_available"} %></p>
      <p>Online? <%= f.check_box :online, options = {:class => "lesson_online"} %></p>
      <%= f.label "Address" %>
      <%= f.text_field :address %><br>
      <%= f.label "City" %>
      <%= f.text_field :city %><br>
      <%= f.label "State" %>
      <%= f.text_field :state %><br>
      <%= f.label "Zipcode" %>
      <%= f.text_field :zipcode %><br>
      <%= f.label "Instructor" %>
      <%= f.collection_select(:instructor_id, Instructor.all.order('name ASC'), :id, :name, prompt: true) %><br>
      <%= f.label "Skill" %>
      <%= f.collection_select(:skill_id, Skill.all.order('name ASC'), :id, :name, prompt: true) %><br>

      <%= f.submit "Submit", class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/lessons/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h3>Edit Lesson</h3>
  </div>
</div>
<%= render 'form', lesson: @lesson %>

app/views/lessons/index.html.erb
<h2>Lessons</h2>

Search for a lesson:
<%= form_tag(lessons_path, method: :get) do %>
  <%= text_field_tag :title %>
  <%= submit_tag 'Search', :class => 'btn btn-primary' %>
<% end %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Lesson</th>
      <th>Instructor</th>
      <th>city</th>
      <th>Price</th>
      <th>Available</th>
      <th>Seats left</th>
    </tr>
  </thead>

  <tbody>
    <% @lessons.each do |lesson| %>
    <tr>
      <td><%= link_to lesson.title, lesson_path(lesson) %></td>
      <td><%= link_to lesson.instructor.name, instructor_path(lesson.instructor) %></td>
      <td><%= lesson.city %></td>
      <td><%= number_to_currency(lesson.price) %></td>
      <td><%= human_boolean(lesson.available) %></td>
      <td><%= lesson.seats %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<% if current_user && current_user.admin %>
    <%= link_to 'New Lesson', new_lesson_path, class: 'btn btn-primary' %>
<% end %>

app/views/lessons/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h3>New Lesson</h3>
  </div>
</div>
<%= render 'form', lesson: @lesson %>

app/views/lessons/show.html.erb
<% if @lesson.errors.any? %>
    <% @lesson.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
<% end %>
<h4><%= link_to "All Sections", sections_path %> > <%= link_to @lesson.skill.section.name, section_path(@lesson.skill.section.id) %> > <%= link_to @lesson.skill.name, skill_path(@lesson.skill.id) %> > <%= @lesson.title %></h4>
<h3><%= @lesson.title %></h3>
<div class="row">
  <div class="col-md-4">
    <div class="wrapper">
      <%= image_tag(@lesson.instructor.picture_url, size: "300x200", alt: "picture") if @lesson.instructor.picture.present? %>
    </div>
  </div>

  <div class="col-md-8 basic-info">
    <div class="instructor-wrapper">
      <%= @lesson.about %><br><br>
      Instructor: <%= link_to @lesson.instructor.name, instructor_path(@lesson.instructor.id) %><br><br>
    </div>
  </div>
</div>

<br>
Price in dollars: <%= number_to_currency(@lesson.price) %><br />
Seats: <%= @lesson.seats %><br />
Dates: <%= @lesson.dates %><br />
Time: <%= @lesson.time %><br />
Length in hours: <%= @lesson.length %> <br />
Requirement: <%= @lesson.requirement %><br />
Available? <%= human_boolean(@lesson.available) %><br />
Online Lesson? <%= human_boolean(@lesson.online) %><br />
Address: <%= @lesson.address %>, <%= @lesson.city %>, <%= @lesson.state %> <%= @lesson.zipcode %><br />
<br>
<% if current_user && current_user.admin %>
    <%= link_to "Edit lesson", edit_lesson_path(@lesson.id), class: 'btn btn-primary' %>
    <%= link_to "Delete lesson", lesson_path(@lesson.id), data: {:confirm => 'Are you sure?'}, method: 'DELETE', class: 'btn btn-primary' %>

<% elsif current_user %>
    Enter student name to book the lesson:
    <%= form_tag("/bookings", method: "post") do %>
        <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
        <%= hidden_field_tag :user_id, current_user.id %>
        <%= hidden_field_tag :lesson_id, @lesson.id %>
        Student Name: <input name="full_name"><br>
        Student Phone: <input name="phone"><br>
        <%= button_tag "Book this lesson", class: 'btn btn-primary' %>
    <% end %>

<% else %>
    <br>
    To book this lesson, please <%= link_to "Sign up", new_user_path %> or
    <%= link_to "Log in", new_session_path %> .
<% end %>