config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'welcome#home'
  get 'signup', to: 'users#new', as: 'signup'
  get '/signin', to: 'sessions#new', as: 'login'
  post '/signin', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  get 'auth/:provider/callback', to: 'sessions#google_auth', as: 'google_login'
  get 'auth/failure', to: redirect('welcome#home')

  get 'welcome/privacy', to: 'welcome#privacy'
  get 'welcome/terms', to: 'welcome#terms'

  resources :users
  resources :sessions, only: [:create, :new]
  resources :lessons
  resources :bookings
  resources :skills
  resources :sections do
    resources :skills, only: [:new, :create]
  end

  resources :instructors do
    resources :reviews, only: [:index, :new, :create]
  end

  get '/rank' => 'instructors#rank', as: 'top3_instructors'
  # resources :instructors do
  #   get 'rank', :on => :collection, as: 'top3'
  # end
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
<div class="container">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
  <a class="navbar-brand" href="<%= root_url %>"> Home</a>
  <a class="navbar-brand" href="/lessons">Lessons</a>
  <a class="navbar-brand" href="/instructors">Instructors</a>
  <a class="navbar-brand" href="/skills">Skills</a>
  <a class="navbar-brand" href="/sections">Sections</a>
</div>
<div class="collapse navbar-collapse">
  <div class="navbar-text pull-right" id="user_header">
    <% if current_user && current_user.admin %>
        <%= link_to "Dashboard", rails_admin_path, class:"navbar-brand"%>
        <%= link_to "Log Out", logout_path, class:"navbar-brand", method:'delete' %>
    <% elsif current_user %>
        <%= link_to "My Lessons", user_path(current_user), class:"navbar-brand"%>
        <%= link_to "Log Out", logout_path, class:"navbar-brand", method:'delete' %>
    <% else %>
        <%= link_to "Sign up", signup_path, class:"navbar-brand" %>
        <%= link_to "Log in", new_session_path, class:"navbar-brand" %>
        <%= link_to "Sign in with Google", "/auth/google_oauth2", class:"navbar-brand" %>
    <% end %>
  </div>
</div>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Book Lessons</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="<%= flash_class(key) %>">
          <%= value %>
        </div>
      <% end %>

      <%= yield %>
    </div>

    <footer class="container footer">
      <nav class="navbar d-flex">
        <ul>
          <li>SUPPORT</li>
          <li><%= link_to "PRIVACY POLICY", welcome_privacy_path %></li>
          <li><%= link_to "TERMS AND CONDITIONS", welcome_terms_path %></li>
          <li>DIRECTORY</li>
          <li>LANGUAGE</li>
        </ul>
        <p> © 2019 BOOK-LESSONS </p>
      </nav>
    </footer>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.js"></script>

  </body>
</html>